name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
        toolchain: stable
        
    - name: Install Trunk
      uses: jetli/trunk-action@v0.5.0
      with:
        version: 'latest'
        
    - name: Build website
      run: |
        chmod +x ./scripts/build_md_lists.sh
        ./scripts/build_md_lists.sh
        trunk build --release
        
    - name: Create CNAME file
      run: echo "amitrahman.me" > ./dist/CNAME
      
    - name: Archive artifact
      run: |
        tar \
          --dereference --hard-dereference \
          --directory "${{ github.workspace }}/dist" \
          -cvf "${{ runner.temp }}/artifact.tar" \
          --exclude=.git \
          --exclude=.github \
          .
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ${{ runner.temp }}/artifact.tar
        retention-days: 1
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
